/*
 * KomMonitor Geocoder Proxy
 * KomMonitor Geocoder Proxy that defines a common query and response interface for arbitrary geocoding services like nominatim, photon (datasource is OSM)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.31
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GeocodingGeometryType model module.
 * @module model/GeocodingGeometryType
 * @version 0.0.1
 */
export class GeocodingGeometryType {
  /**
   * Constructs a new <code>GeocodingGeometryType</code>.
   * @alias module:model/GeocodingGeometryType
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GeocodingGeometryType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GeocodingGeometryType} obj Optional instance to populate.
   * @return {module:model/GeocodingGeometryType} The populated <code>GeocodingGeometryType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GeocodingGeometryType();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('coordinates'))
        obj.coordinates = ApiClient.convertToType(data['coordinates'], ['Number']);
    }
    return obj;
  }
}

/**
 * the geometry type of the feature - here in geocoding context it is always point
 * @member {String} type
 * @default 'Point'
 */
GeocodingGeometryType.prototype.type = 'Point';

/**
 * coordinate array of feature point geometry using longitude, latitude
 * @member {Array.<Number>} coordinates
 */
GeocodingGeometryType.prototype.coordinates = undefined;

