/*
 * KomMonitor Geocoder Proxy
 * KomMonitor Geocoder Proxy that defines a common query and response interface for arbitrary geocoding services like nominatim, photon (datasource is OSM)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.31
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GeocodingGeometryType} from './GeocodingGeometryType';
import {GeocodingPropertiesType} from './GeocodingPropertiesType';

/**
 * The GeocodingFeatureType model module.
 * @module model/GeocodingFeatureType
 * @version 0.0.1
 */
export class GeocodingFeatureType {
  /**
   * Constructs a new <code>GeocodingFeatureType</code>.
   * @alias module:model/GeocodingFeatureType
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GeocodingFeatureType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GeocodingFeatureType} obj Optional instance to populate.
   * @return {module:model/GeocodingFeatureType} The populated <code>GeocodingFeatureType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GeocodingFeatureType();
      if (data.hasOwnProperty('geometry'))
        obj.geometry = GeocodingGeometryType.constructFromObject(data['geometry']);
      if (data.hasOwnProperty('properties'))
        obj.properties = GeocodingPropertiesType.constructFromObject(data['properties']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GeocodingGeometryType} geometry
 */
GeocodingFeatureType.prototype.geometry = undefined;

/**
 * @member {module:model/GeocodingPropertiesType} properties
 */
GeocodingFeatureType.prototype.properties = undefined;

