"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.GeocodingOutputType = void 0;

var _ApiClient = require("../ApiClient");

var _GeocodingFeatureType = require("./GeocodingFeatureType");

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }

/**
 * The GeocodingOutputType model module.
 * @module model/GeocodingOutputType
 * @version 0.0.1
 */
var GeocodingOutputType = /*#__PURE__*/function () {
  /**
   * Constructs a new <code>GeocodingOutputType</code>.
   * output generated by a geocoding request. 0 or more records in the form of a GeoJSON FeatureCollection (if emtpy then the returned FeatureCollection has an empty features array)
   * @alias module:model/GeocodingOutputType
   * @class
   */
  function GeocodingOutputType() {
    _classCallCheck(this, GeocodingOutputType);
  }
  /**
   * Constructs a <code>GeocodingOutputType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GeocodingOutputType} obj Optional instance to populate.
   * @return {module:model/GeocodingOutputType} The populated <code>GeocodingOutputType</code> instance.
   */


  _createClass(GeocodingOutputType, null, [{
    key: "constructFromObject",
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new GeocodingOutputType();
        if (data.hasOwnProperty('type')) obj.type = _ApiClient.ApiClient.convertToType(data['type'], 'String');
        if (data.hasOwnProperty('features')) obj.features = _ApiClient.ApiClient.convertToType(data['features'], [_GeocodingFeatureType.GeocodingFeatureType]);
      }

      return obj;
    }
  }]);

  return GeocodingOutputType;
}();
/**
 * @member {String} type
 * @default 'FeatureCollection'
 */


exports.GeocodingOutputType = GeocodingOutputType;
GeocodingOutputType.prototype.type = 'FeatureCollection';
/**
 * @member {Array.<module:model/GeocodingFeatureType>} features
 */

GeocodingOutputType.prototype.features = undefined;