/*
 * KomMonitor Geocoder Proxy
 * KomMonitor Geocoder Proxy that defines a common query and response interface for arbitrary geocoding services like nominatim, photon (datasource is OSM)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.31
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KomMonitorGeocoderProxy);
  }
}(this, function(expect, KomMonitorGeocoderProxy) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GeocodingFeatureType', function() {
      beforeEach(function() {
        instance = new KomMonitorGeocoderProxy.GeocodingFeatureType();
      });

      it('should create an instance of GeocodingFeatureType', function() {
        // TODO: update the code to test GeocodingFeatureType
        expect(instance).to.be.a(KomMonitorGeocoderProxy.GeocodingFeatureType);
      });

      it('should have the property geometry (base name: "geometry")', function() {
        // TODO: update the code to test the property geometry
        expect(instance).to.have.property('geometry');
        // expect(instance.geometry).to.be(expectedValueLiteral);
      });

      it('should have the property properties (base name: "properties")', function() {
        // TODO: update the code to test the property properties
        expect(instance).to.have.property('properties');
        // expect(instance.properties).to.be(expectedValueLiteral);
      });

    });
  });

}));
