/*
 * KomMonitor Geocoder Proxy
 * KomMonitor Geocoder Proxy that defines a common query and response interface for arbitrary geocoding services like nominatim, photon (datasource is OSM)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.31
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KomMonitorGeocoderProxy);
  }
}(this, function(expect, KomMonitorGeocoderProxy) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KomMonitorGeocoderProxy.ReverseGeocodeApi();
  });

  describe('(package)', function() {
    describe('ReverseGeocodeApi', function() {
      describe('reverseGeocode', function() {
        it('should call reverseGeocode successfully', function(done) {
          // TODO: uncomment, update parameter values for reverseGeocode call and complete the assertions
          /*

          instance.reverseGeocode(lon, lat, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(KomMonitorGeocoderProxy.GeocodingOutputType);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
